name: phylogeny
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - mafft=7.520
  - trimal=1.4.1
  - iqtree=2.2.5
  - snakemake=7.32.4
  - ete3=3.1.2
  - blast=2.14.1
  - python=3.11.5
