name: phylogeny
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - mafft=7.486
  - trimal=1.4.1
  - iqtree=2.1.2
  - snakemake=6.6.1
  - ete3=3.1.2
  - blast=2.12.0
  - python=3.10.2
